### ISSUE TITLE
[Feature Request] Please upload version for forge 1.19.2 to modrinth

### ISSUE THREAD

**Issue by ghost** [nanite/Yeetus-Experimentus#2]
### Feature Description

I am working on a forge 1.19.2 modrinth pack while boycotting cf it would be really helpful

**Comment by ildiem** [comment]
+1 for this, please

**Comment by ColonelGerdauf** [comment]
I am for this as well. Not really for any quasi-political motives, but due to the practicalities of Modrinth having a more efficient API for downloads and updates than CurseForge.
