### ISSUE TITLE
Incompatibility 1.20.4 [Issue]

### ISSUE THREAD

**Issue by krafg** [nanite/Yeetus-Experimentus#4]
### Minecraft Version

1.20.4

### Modloader

Fabric

### Mod version

2.3.1

### Latest version?

- [X] Yes

### Repeatable?

- [X] Yes

### Link to log files

[crash-2024-01-02_13.02.52-client.txt](https://github.com/nanite/Yeetus-Experimentus/files/13811762/crash-2024-01-02_13.02.52-client.txt)

### Description of the issue you are having

Game crashes when try to load a world.

### Information

- [X] I have provided as much information as possible

**Comment by MichaelHillcox** [comment]
It's not been updated yet

**Comment by krafg** [comment]
So, needs to be updated.
