### ISSUE TITLE
[Issue] NeoForge 1.20.4: Mod does not work

### ISSUE THREAD

**Issue by MSandro** [nanite/Yeetus-Experimentus#5]
### Minecraft Version

1.20.4

### Modloader

neoforge-20.4.223

### Mod version

yeetusexperimentus-neoforge-84.0.1

### Latest version?

- [X] Yes

### Repeatable?

- [X] Yes

### Link to log files

https://gist.github.com/MSandro/020b64fc451d148e75c5b9a5bf9e4d23

### Steps to reproduce the issue

* launch the game

### Description of the issue you are having

* launch the game
* the mod shows up in the mod list
* create a new world with experimental features (e.g. enable 1.21 Features)
* get the experimental warning message

### Information

- [X] I have provided as much information as possible

**Comment by MichaelHillcox** [comment]
https://www.curseforge.com/minecraft/mc-mods/yeetusexperimentus/files/5415033
